language: node_js
node_js:
  - "node"
cache:
  directories:
    - client/node_modules
	- server/node_modules
script:
  - cd server && npm install
  - cd ../client && npm install
  - npm test
  - npm run build
# deploy:
#   provider: surge
#   project: ./client/build
#   domain: wesleyamaro-readable.surge.sh
